domains:
  - id: 1
    name: shopsys
    locale: en

  - id: 2
    name: 2.shopsys
    locale: cs
    styles_directory: domain2

  - id: 3
    name: 3.shopsys
    locale: sk
    styles_directory: domain2
